### ISSUE TITLE
Wrong message for skipping/executing setup

### ISSUE THREAD

**Issue by ambrt** [fauna-brecht/fwitter#10]
Hi

I'm working through setup script and noted that fwitter uses
```
 await handleSetupError(
      client.query(If(Exists(Database(childDbName)), false, CreateDatabase({ name: childDbName }))),
      'database - create child database'
    )
```
https://github.com/fauna-brecht/fwitter/blob/master/scripts/setup.js#L58

The thing is that in case of existing database, the error handler get just `false` value from correctly resolved promise - so there is no error to catch as far as handler is concerned.

In effect, handler doesn't report "Skipping- instance already exists" but reports "[Executed]..." every time.

It should be just:
```
client.query(CreateDatabase({ name: childDbName }))
```
to report creating or skipping correctly.

**Comment by fauna-brecht** [comment]
Good point, I'll keep this issue open in case I have time to come back to this project.
