### ISSUE TITLE
GraphQL?

### ISSUE THREAD

**Issue by bessfernandez** [fauna-brecht/fwitter#11]
Any chance this app / tutorial will one day demonstrate importing a GraphQL schema and using GraphQL in the app? 👯 

(I have loved following this to learn more FQL but would also love to see a sample GraphQL schema and how FQL might handle more complex indexing / functions in the client)

**Comment by fauna-brecht** [comment]
Not this specific app but we plan to create a GraphQL sample soon which will demonstrate how to use GraphQL and FQL together. Given that I'm no longer the only DA @ Fauna, things will accelarate :)
