### ISSUE TITLE
Editing Fweets

### ISSUE THREAD

**Issue by codeghees** [fauna-brecht/fwitter#12]
How would I go about building an edit Fweet functionality?

**Comment by fauna-brecht** [comment]
I just pushed the staging branch to main, there is an example to update the user profile in there. That might clarify it a little bit? Editing a fweet would be similar. 
You would write a role to specify that you can only edit a fweet where the owner of the fweet equals the CurrentIdentity() (iirc there is a reference to the original creator stored on the fweet)
