### ISSUE TITLE
Awesome As (No Issue, Just Praise)

### ISSUE THREAD

**Issue by fullakingi** [fauna-brecht/fwitter#13]
Just some positive words of thanks in case the OG devs visit here. This work is greatly appreciated. To be honest I don't really understand the syntax of React and the configuration but I understand the relationships between parts and I can see how efficient Fauna is at registering changes in the front-end to the back-end.  This demo is really kick-ass. 🤙

**Comment by fauna-brecht** [comment]
```_____$$$$_________$$$$
___$$$$$$$$_____$$$$$$$$
_$$$$$$$$$$$$_$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$
_$$$$$$$$$$$$$$$$$$$$$$$$$
__$$$$$$$$$$$$$$$$$$$$$$$
____$$$$$$$$$$$$$$$$$$$
_______$$$$$$$$$$$$$
__________$$$$$$$
____________$$$
_____________$
```

Much appreciated
